export const ROLES = [
  'Director',
  'Operation Manager',
  'Sales Admin',
  'Branch Manager',
  'Sales Manager',
  'Marketing Manager',
  'Customer Manager',
  'Support Manager',
  'Team Leader',
  'Customer Team Leader',
  'Support Team Leader',
  'Marketing Moderator',
  'Sales Person',
  'Customer Agent',
  'Support Agent',
  'Custom',
];

export const STATUSES = ['Active', 'Inactive', 'Suspended'];

export const MOCK_MANAGERS = [
  { id: 'u-1', name: 'Ahmed Admin', role: 'Sales Admin' },
  { id: 'u-2', name: 'Sarah Branch', role: 'Branch Manager' },
  { id: 'u-3', name: 'Mohamed Branch', role: 'Branch Manager' },
  { id: 'u-4', name: 'Khaled Admin', role: 'Sales Admin' },
  { id: 'u-5', name: 'Hassan Sales', role: 'Sales Manager' },
  { id: 'u-6', name: 'Omar Sales', role: 'Sales Manager' },
  { id: 'u-7', name: 'Mona Team', role: 'Team Leader' },
  { id: 'u-8', name: 'Ali Team', role: 'Team Leader' },
  { id: 'u-9', name: 'Youssef Director', role: 'Director' },
  { id: 'u-10', name: 'Layla Operation', role: 'Operation Manager' },
];

export const ROLE_HIERARCHY = {
  'Sales Manager': ['Sales Admin', 'Branch Manager'],
  'Team Leader': ['Sales Manager', 'Branch Manager', 'Sales Admin'],
  'Sales Person': ['Team Leader', 'Sales Manager', 'Branch Manager', 'Sales Admin'],
  'Marketing Manager': ['Director', 'Operation Manager'],
};

export const PERMISSIONS = {
  Leads: ['addLead','showCreator','editInfo','editPhone','importLeads','exportLeads'],
  Inventory: ['addItems', 'addProject', 'addProperties', 'addBroker', 'addDeveloper', 'showRequests'],
  Marketing: ['showMarketingDashboard', 'showCampaign', 'addLandingPage', 'integration'],
  Customers: ['showCustomerModule', 'convertLeadToCustomer', 'addNewCustomer', 'editCustomer', 'deleteCustomer'],
  Support: ['addTickets','sla','editInfo','exportReports','convertFromCustomer','convertFromLead','reports','deleteTickets'],
  Control: ['addRegions','addArea','addStage','addSource','userManagement','multiAction','salesComment','allowActionOnTeam','assignLeads','editConfigurationSettings','addInputs'],
};

export const REPORT_MODULES = [
  'Leads Pipeline',
  'Sales Activities',
  'Meetings Report',
  'Reservations Report',
  'Closed Deals',
  'Rent Report',
  'Proposals Report',
  'Check In Report',
  'Customers Report',
  'Targets & Revenue',
  'Imports Report',
  'Exports Report'
];

export const PERM_LABELS_AR = {
  groups: {
    Leads: 'الليدز',
    Inventory: 'المخزون',
    Marketing: 'التسويق',
    Customers: 'العملاء',
    Support: 'الدعم',
    Control: 'التحكم',
    Reports: 'التقارير',
  },
  report_modules: {
    'Leads Pipeline': 'بايبلاين الليدز',
    'Sales Activities': 'نشاطات المبيعات',
    'Meetings Report': 'تقرير الاجتماعات',
    'Reservations Report': 'تقرير الحجوزات',
    'Closed Deals': 'الصفقات المغلقة',
    'Rent Report': 'تقرير الإيجارات',
    'Proposals Report': 'تقرير العروض',
    'Check In Report': 'تقرير تسجيل الدخول',
    'Customers Report': 'تقرير العملاء',
    'Targets & Revenue': 'الأهداف والإيرادات',
    'Imports Report': 'تقرير الاستيراد',
    'Exports Report': 'تقرير التصدير',
  },
  actions: {
    view: 'عرض',
    create: 'إنشاء',
    assign: 'تعيين',
    addLead: 'إضافة ليد',
    addInputs: 'إضافة إدخالات',
    showCreator: 'عرض المنشئ',
    editPhone: 'تعديل الهاتف',
    showCampaigns: 'عرض الحملات',
    addLandingPages: 'إضافة صفحات هبوط',
    integrations: 'التكاملات',
    exportReports: 'تصدير التقارير',
    showReports: 'عرض التقارير',
    showCustomerModule: 'عرض موديول العملاء',
    convertLeadToCustomer: 'تحويل ليد إلى عميل',
    addNewCustomer: 'إضافة عميل جديد',
    editCustomer: 'تعديل عميل',
    convertFromLead: 'تحويل من ليد',
    addCustomer: 'إضافة عميل',
    editInfo: 'تعديل البيانات',
    deleteCustomer: 'حذف العميل',
    showModule: 'عرض الموديول',
    addTickets: 'إضافة تذاكر',
    sla: 'اتفاقية مستوى الخدمة',
    convertFromCustomer: 'تحويل من عميل',
    reports: 'التقارير',
    deleteTickets: 'حذف التذاكر',
    addRegions: 'إضافة مناطق',
    addArea: 'إضافة منطقة',
    addStage: 'إضافة مرحلة',
    addSource: 'إضافة مصدر',
    userManagement: 'إدارة المستخدمين',
    multiAction: 'أكشنات متعددة',
    salesComment: 'تعليق مبيعات',
    allowActionOnTeam: 'السماح بالأكشن على الفريق',
    assignLeads: 'تعيين ليدز',
    importLeads: 'استيراد ليدز',
    exportLeads: 'تصدير ليدز',
    addDepartment: 'إضافة قسم',
    editConfigurationSettings: 'تعديل إعدادات الكونفيجوريشن',
    addProducts: 'إضافة منتجات',
    addItems: 'إضافة عناصر',
    addSuppliers: 'إضافة موردين',
    addWarehouse: 'إضافة مخزن',
    showTransaction: 'عرض الحركات',
    addProject: 'إضافة مشروع',
    addUnits: 'إضافة وحدات',
    addProperties: 'إضافة عقارات',
    addBroker: 'إضافة وسيط',
    addDeveloper: 'إضافة مطور',
    showRequests: 'عرض الطلبات',
    showMarketingDashboard: 'عرض لوحة التسويق',
    showCampaign: 'عرض الحملة',
    addLandingPage: 'إضافة صفحة هبوط',
    integration: 'التكامل',
  }
};
